# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pbft_pb2 as pbft__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pbft_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PBFTServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClientTransaction = channel.unary_unary(
                '/PBFTService/ClientTransaction',
                request_serializer=pbft__pb2.ClientTransactionRequest.SerializeToString,
                response_deserializer=pbft__pb2.ClientTransactionResponse.FromString,
                _registered_method=True)
        self.ReplicaPrePrepare = channel.unary_unary(
                '/PBFTService/ReplicaPrePrepare',
                request_serializer=pbft__pb2.PrePrepareRequest.SerializeToString,
                response_deserializer=pbft__pb2.PrePrepareResponse.FromString,
                _registered_method=True)
        self.Prepare = channel.unary_unary(
                '/PBFTService/Prepare',
                request_serializer=pbft__pb2.PrepareRequest.SerializeToString,
                response_deserializer=pbft__pb2.PrepareResponse.FromString,
                _registered_method=True)
        self.PrepareBroadcast = channel.unary_unary(
                '/PBFTService/PrepareBroadcast',
                request_serializer=pbft__pb2.PrepareBroadcastRequest.SerializeToString,
                response_deserializer=pbft__pb2.PrepareBroadcastResponse.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/PBFTService/Commit',
                request_serializer=pbft__pb2.CommitRequest.SerializeToString,
                response_deserializer=pbft__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.CommitBroadcast = channel.unary_unary(
                '/PBFTService/CommitBroadcast',
                request_serializer=pbft__pb2.CommitBroadcastRequest.SerializeToString,
                response_deserializer=pbft__pb2.CommitBroadcastResponse.FromString,
                _registered_method=True)
        self.ResetServerState = channel.unary_unary(
                '/PBFTService/ResetServerState',
                request_serializer=pbft__pb2.ResetServerStateRequest.SerializeToString,
                response_deserializer=pbft__pb2.ResetServerStateResponse.FromString,
                _registered_method=True)
        self.GetServerBalances = channel.unary_unary(
                '/PBFTService/GetServerBalances',
                request_serializer=pbft__pb2.BalancesRequest.SerializeToString,
                response_deserializer=pbft__pb2.BalancesResponse.FromString,
                _registered_method=True)
        self.ViewChange = channel.unary_unary(
                '/PBFTService/ViewChange',
                request_serializer=pbft__pb2.ViewChangeRequest.SerializeToString,
                response_deserializer=pbft__pb2.ViewChangeResponse.FromString,
                _registered_method=True)
        self.NewView = channel.unary_unary(
                '/PBFTService/NewView',
                request_serializer=pbft__pb2.NewViewRequest.SerializeToString,
                response_deserializer=pbft__pb2.NewViewResponse.FromString,
                _registered_method=True)
        self.PrintLog = channel.unary_unary(
                '/PBFTService/PrintLog',
                request_serializer=pbft__pb2.PrintLogRequest.SerializeToString,
                response_deserializer=pbft__pb2.PrintLogResponse.FromString,
                _registered_method=True)
        self.PrintStatus = channel.unary_unary(
                '/PBFTService/PrintStatus',
                request_serializer=pbft__pb2.PrintStatusRequest.SerializeToString,
                response_deserializer=pbft__pb2.PrintStatusResponse.FromString,
                _registered_method=True)
        self.PrintView = channel.unary_unary(
                '/PBFTService/PrintView',
                request_serializer=pbft__pb2.PrintViewRequest.SerializeToString,
                response_deserializer=pbft__pb2.PrintViewResponse.FromString,
                _registered_method=True)
        self.ChangeServerTimeout = channel.unary_unary(
                '/PBFTService/ChangeServerTimeout',
                request_serializer=pbft__pb2.ChangeServerTimeoutRequest.SerializeToString,
                response_deserializer=pbft__pb2.ChangeServerTimeoutResponse.FromString,
                _registered_method=True)


class PBFTServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClientTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicaPrePrepare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prepare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareBroadcast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitBroadcast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetServerState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerBalances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrintLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrintStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrintView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeServerTimeout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PBFTServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClientTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientTransaction,
                    request_deserializer=pbft__pb2.ClientTransactionRequest.FromString,
                    response_serializer=pbft__pb2.ClientTransactionResponse.SerializeToString,
            ),
            'ReplicaPrePrepare': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicaPrePrepare,
                    request_deserializer=pbft__pb2.PrePrepareRequest.FromString,
                    response_serializer=pbft__pb2.PrePrepareResponse.SerializeToString,
            ),
            'Prepare': grpc.unary_unary_rpc_method_handler(
                    servicer.Prepare,
                    request_deserializer=pbft__pb2.PrepareRequest.FromString,
                    response_serializer=pbft__pb2.PrepareResponse.SerializeToString,
            ),
            'PrepareBroadcast': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareBroadcast,
                    request_deserializer=pbft__pb2.PrepareBroadcastRequest.FromString,
                    response_serializer=pbft__pb2.PrepareBroadcastResponse.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=pbft__pb2.CommitRequest.FromString,
                    response_serializer=pbft__pb2.CommitResponse.SerializeToString,
            ),
            'CommitBroadcast': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitBroadcast,
                    request_deserializer=pbft__pb2.CommitBroadcastRequest.FromString,
                    response_serializer=pbft__pb2.CommitBroadcastResponse.SerializeToString,
            ),
            'ResetServerState': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetServerState,
                    request_deserializer=pbft__pb2.ResetServerStateRequest.FromString,
                    response_serializer=pbft__pb2.ResetServerStateResponse.SerializeToString,
            ),
            'GetServerBalances': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerBalances,
                    request_deserializer=pbft__pb2.BalancesRequest.FromString,
                    response_serializer=pbft__pb2.BalancesResponse.SerializeToString,
            ),
            'ViewChange': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewChange,
                    request_deserializer=pbft__pb2.ViewChangeRequest.FromString,
                    response_serializer=pbft__pb2.ViewChangeResponse.SerializeToString,
            ),
            'NewView': grpc.unary_unary_rpc_method_handler(
                    servicer.NewView,
                    request_deserializer=pbft__pb2.NewViewRequest.FromString,
                    response_serializer=pbft__pb2.NewViewResponse.SerializeToString,
            ),
            'PrintLog': grpc.unary_unary_rpc_method_handler(
                    servicer.PrintLog,
                    request_deserializer=pbft__pb2.PrintLogRequest.FromString,
                    response_serializer=pbft__pb2.PrintLogResponse.SerializeToString,
            ),
            'PrintStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.PrintStatus,
                    request_deserializer=pbft__pb2.PrintStatusRequest.FromString,
                    response_serializer=pbft__pb2.PrintStatusResponse.SerializeToString,
            ),
            'PrintView': grpc.unary_unary_rpc_method_handler(
                    servicer.PrintView,
                    request_deserializer=pbft__pb2.PrintViewRequest.FromString,
                    response_serializer=pbft__pb2.PrintViewResponse.SerializeToString,
            ),
            'ChangeServerTimeout': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeServerTimeout,
                    request_deserializer=pbft__pb2.ChangeServerTimeoutRequest.FromString,
                    response_serializer=pbft__pb2.ChangeServerTimeoutResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PBFTService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PBFTService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PBFTService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClientTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFTService/ClientTransaction',
            pbft__pb2.ClientTransactionRequest.SerializeToString,
            pbft__pb2.ClientTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicaPrePrepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFTService/ReplicaPrePrepare',
            pbft__pb2.PrePrepareRequest.SerializeToString,
            pbft__pb2.PrePrepareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Prepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFTService/Prepare',
            pbft__pb2.PrepareRequest.SerializeToString,
            pbft__pb2.PrepareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareBroadcast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFTService/PrepareBroadcast',
            pbft__pb2.PrepareBroadcastRequest.SerializeToString,
            pbft__pb2.PrepareBroadcastResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFTService/Commit',
            pbft__pb2.CommitRequest.SerializeToString,
            pbft__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitBroadcast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFTService/CommitBroadcast',
            pbft__pb2.CommitBroadcastRequest.SerializeToString,
            pbft__pb2.CommitBroadcastResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetServerState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFTService/ResetServerState',
            pbft__pb2.ResetServerStateRequest.SerializeToString,
            pbft__pb2.ResetServerStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerBalances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFTService/GetServerBalances',
            pbft__pb2.BalancesRequest.SerializeToString,
            pbft__pb2.BalancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFTService/ViewChange',
            pbft__pb2.ViewChangeRequest.SerializeToString,
            pbft__pb2.ViewChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NewView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFTService/NewView',
            pbft__pb2.NewViewRequest.SerializeToString,
            pbft__pb2.NewViewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrintLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFTService/PrintLog',
            pbft__pb2.PrintLogRequest.SerializeToString,
            pbft__pb2.PrintLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrintStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFTService/PrintStatus',
            pbft__pb2.PrintStatusRequest.SerializeToString,
            pbft__pb2.PrintStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrintView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFTService/PrintView',
            pbft__pb2.PrintViewRequest.SerializeToString,
            pbft__pb2.PrintViewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeServerTimeout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PBFTService/ChangeServerTimeout',
            pbft__pb2.ChangeServerTimeoutRequest.SerializeToString,
            pbft__pb2.ChangeServerTimeoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
