# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import transactions_pb2 as transactions__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in transactions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TransactionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transact = channel.unary_unary(
                '/transactions.TransactionService/Transact',
                request_serializer=transactions__pb2.TransactionRequest.SerializeToString,
                response_deserializer=transactions__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.Promise = channel.unary_unary(
                '/transactions.TransactionService/Promise',
                request_serializer=transactions__pb2.PromiseRequest.SerializeToString,
                response_deserializer=transactions__pb2.PromiseResponse.FromString,
                _registered_method=True)
        self.Acknowledge = channel.unary_unary(
                '/transactions.TransactionService/Acknowledge',
                request_serializer=transactions__pb2.AcknowledgeRequest.SerializeToString,
                response_deserializer=transactions__pb2.AcknowledgeResponse.FromString,
                _registered_method=True)
        self.Accept = channel.unary_unary(
                '/transactions.TransactionService/Accept',
                request_serializer=transactions__pb2.AcceptRequest.SerializeToString,
                response_deserializer=transactions__pb2.AcceptResponse.FromString,
                _registered_method=True)
        self.Accepted = channel.unary_unary(
                '/transactions.TransactionService/Accepted',
                request_serializer=transactions__pb2.AcceptedRequest.SerializeToString,
                response_deserializer=transactions__pb2.AcceptedResponse.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/transactions.TransactionService/Commit',
                request_serializer=transactions__pb2.CommitRequest.SerializeToString,
                response_deserializer=transactions__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/transactions.TransactionService/GetBalance',
                request_serializer=transactions__pb2.GetBalanceRequest.SerializeToString,
                response_deserializer=transactions__pb2.GetBalanceResponse.FromString,
                _registered_method=True)
        self.GetLogs = channel.unary_unary(
                '/transactions.TransactionService/GetLogs',
                request_serializer=transactions__pb2.GetLogRequest.SerializeToString,
                response_deserializer=transactions__pb2.GetLogResponse.FromString,
                _registered_method=True)
        self.GetDB = channel.unary_unary(
                '/transactions.TransactionService/GetDB',
                request_serializer=transactions__pb2.GetDBRequest.SerializeToString,
                response_deserializer=transactions__pb2.GetDBResponse.FromString,
                _registered_method=True)
        self.UpdateDB = channel.unary_unary(
                '/transactions.TransactionService/UpdateDB',
                request_serializer=transactions__pb2.UpdateDBRequest.SerializeToString,
                response_deserializer=transactions__pb2.UpdateDBResponse.FromString,
                _registered_method=True)
        self.GetPendingTransactions = channel.unary_unary(
                '/transactions.TransactionService/GetPendingTransactions',
                request_serializer=transactions__pb2.GetPendingTransactionsRequest.SerializeToString,
                response_deserializer=transactions__pb2.GetPendingTransactionsResponse.FromString,
                _registered_method=True)
        self.SetPendingTransactions = channel.unary_unary(
                '/transactions.TransactionService/SetPendingTransactions',
                request_serializer=transactions__pb2.SetPendingTransactionsRequest.SerializeToString,
                response_deserializer=transactions__pb2.SetPendingTransactionsResponse.FromString,
                _registered_method=True)
        self.SendDataStore = channel.unary_unary(
                '/transactions.TransactionService/SendDataStore',
                request_serializer=transactions__pb2.SendDataStoreRequest.SerializeToString,
                response_deserializer=transactions__pb2.SendDataStoreResponse.FromString,
                _registered_method=True)
        self.ModifyDataStore = channel.unary_unary(
                '/transactions.TransactionService/ModifyDataStore',
                request_serializer=transactions__pb2.ModifyDataStoreRequest.SerializeToString,
                response_deserializer=transactions__pb2.ModifyDataStoreResponse.FromString,
                _registered_method=True)
        self.Catchup = channel.unary_unary(
                '/transactions.TransactionService/Catchup',
                request_serializer=transactions__pb2.CatchupRequest.SerializeToString,
                response_deserializer=transactions__pb2.CatchupResponse.FromString,
                _registered_method=True)


class TransactionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Transact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Promise(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Acknowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Accept(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Accepted(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDB(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDB(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingTransactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPendingTransactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendDataStore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyDataStore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Catchup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transact': grpc.unary_unary_rpc_method_handler(
                    servicer.Transact,
                    request_deserializer=transactions__pb2.TransactionRequest.FromString,
                    response_serializer=transactions__pb2.TransactionResponse.SerializeToString,
            ),
            'Promise': grpc.unary_unary_rpc_method_handler(
                    servicer.Promise,
                    request_deserializer=transactions__pb2.PromiseRequest.FromString,
                    response_serializer=transactions__pb2.PromiseResponse.SerializeToString,
            ),
            'Acknowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.Acknowledge,
                    request_deserializer=transactions__pb2.AcknowledgeRequest.FromString,
                    response_serializer=transactions__pb2.AcknowledgeResponse.SerializeToString,
            ),
            'Accept': grpc.unary_unary_rpc_method_handler(
                    servicer.Accept,
                    request_deserializer=transactions__pb2.AcceptRequest.FromString,
                    response_serializer=transactions__pb2.AcceptResponse.SerializeToString,
            ),
            'Accepted': grpc.unary_unary_rpc_method_handler(
                    servicer.Accepted,
                    request_deserializer=transactions__pb2.AcceptedRequest.FromString,
                    response_serializer=transactions__pb2.AcceptedResponse.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=transactions__pb2.CommitRequest.FromString,
                    response_serializer=transactions__pb2.CommitResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=transactions__pb2.GetBalanceRequest.FromString,
                    response_serializer=transactions__pb2.GetBalanceResponse.SerializeToString,
            ),
            'GetLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogs,
                    request_deserializer=transactions__pb2.GetLogRequest.FromString,
                    response_serializer=transactions__pb2.GetLogResponse.SerializeToString,
            ),
            'GetDB': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDB,
                    request_deserializer=transactions__pb2.GetDBRequest.FromString,
                    response_serializer=transactions__pb2.GetDBResponse.SerializeToString,
            ),
            'UpdateDB': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDB,
                    request_deserializer=transactions__pb2.UpdateDBRequest.FromString,
                    response_serializer=transactions__pb2.UpdateDBResponse.SerializeToString,
            ),
            'GetPendingTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingTransactions,
                    request_deserializer=transactions__pb2.GetPendingTransactionsRequest.FromString,
                    response_serializer=transactions__pb2.GetPendingTransactionsResponse.SerializeToString,
            ),
            'SetPendingTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPendingTransactions,
                    request_deserializer=transactions__pb2.SetPendingTransactionsRequest.FromString,
                    response_serializer=transactions__pb2.SetPendingTransactionsResponse.SerializeToString,
            ),
            'SendDataStore': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDataStore,
                    request_deserializer=transactions__pb2.SendDataStoreRequest.FromString,
                    response_serializer=transactions__pb2.SendDataStoreResponse.SerializeToString,
            ),
            'ModifyDataStore': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyDataStore,
                    request_deserializer=transactions__pb2.ModifyDataStoreRequest.FromString,
                    response_serializer=transactions__pb2.ModifyDataStoreResponse.SerializeToString,
            ),
            'Catchup': grpc.unary_unary_rpc_method_handler(
                    servicer.Catchup,
                    request_deserializer=transactions__pb2.CatchupRequest.FromString,
                    response_serializer=transactions__pb2.CatchupResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transactions.TransactionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('transactions.TransactionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TransactionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Transact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transactions.TransactionService/Transact',
            transactions__pb2.TransactionRequest.SerializeToString,
            transactions__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Promise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transactions.TransactionService/Promise',
            transactions__pb2.PromiseRequest.SerializeToString,
            transactions__pb2.PromiseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Acknowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transactions.TransactionService/Acknowledge',
            transactions__pb2.AcknowledgeRequest.SerializeToString,
            transactions__pb2.AcknowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Accept(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transactions.TransactionService/Accept',
            transactions__pb2.AcceptRequest.SerializeToString,
            transactions__pb2.AcceptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Accepted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transactions.TransactionService/Accepted',
            transactions__pb2.AcceptedRequest.SerializeToString,
            transactions__pb2.AcceptedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transactions.TransactionService/Commit',
            transactions__pb2.CommitRequest.SerializeToString,
            transactions__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transactions.TransactionService/GetBalance',
            transactions__pb2.GetBalanceRequest.SerializeToString,
            transactions__pb2.GetBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transactions.TransactionService/GetLogs',
            transactions__pb2.GetLogRequest.SerializeToString,
            transactions__pb2.GetLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transactions.TransactionService/GetDB',
            transactions__pb2.GetDBRequest.SerializeToString,
            transactions__pb2.GetDBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transactions.TransactionService/UpdateDB',
            transactions__pb2.UpdateDBRequest.SerializeToString,
            transactions__pb2.UpdateDBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transactions.TransactionService/GetPendingTransactions',
            transactions__pb2.GetPendingTransactionsRequest.SerializeToString,
            transactions__pb2.GetPendingTransactionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPendingTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transactions.TransactionService/SetPendingTransactions',
            transactions__pb2.SetPendingTransactionsRequest.SerializeToString,
            transactions__pb2.SetPendingTransactionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendDataStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transactions.TransactionService/SendDataStore',
            transactions__pb2.SendDataStoreRequest.SerializeToString,
            transactions__pb2.SendDataStoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModifyDataStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transactions.TransactionService/ModifyDataStore',
            transactions__pb2.ModifyDataStoreRequest.SerializeToString,
            transactions__pb2.ModifyDataStoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Catchup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transactions.TransactionService/Catchup',
            transactions__pb2.CatchupRequest.SerializeToString,
            transactions__pb2.CatchupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
