# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import project4_pb2 as project4__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in project4_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class project4ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClientTransaction = channel.unary_unary(
                '/project4Service/ClientTransaction',
                request_serializer=project4__pb2.ClientTransactionRequest.SerializeToString,
                response_deserializer=project4__pb2.ClientTransactionResponse.FromString,
                _registered_method=True)
        self.ReplicaPrePrepare = channel.unary_unary(
                '/project4Service/ReplicaPrePrepare',
                request_serializer=project4__pb2.PrePrepareRequest.SerializeToString,
                response_deserializer=project4__pb2.PrePrepareResponse.FromString,
                _registered_method=True)
        self.Prepare = channel.unary_unary(
                '/project4Service/Prepare',
                request_serializer=project4__pb2.PrepareRequest.SerializeToString,
                response_deserializer=project4__pb2.PrepareResponse.FromString,
                _registered_method=True)
        self.PrepareBroadcast = channel.unary_unary(
                '/project4Service/PrepareBroadcast',
                request_serializer=project4__pb2.PrepareBroadcastRequest.SerializeToString,
                response_deserializer=project4__pb2.PrepareBroadcastResponse.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/project4Service/Commit',
                request_serializer=project4__pb2.CommitRequest.SerializeToString,
                response_deserializer=project4__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.CommitBroadcast = channel.unary_unary(
                '/project4Service/CommitBroadcast',
                request_serializer=project4__pb2.CommitBroadcastRequest.SerializeToString,
                response_deserializer=project4__pb2.CommitBroadcastResponse.FromString,
                _registered_method=True)
        self.ResetServerState = channel.unary_unary(
                '/project4Service/ResetServerState',
                request_serializer=project4__pb2.ResetServerStateRequest.SerializeToString,
                response_deserializer=project4__pb2.ResetServerStateResponse.FromString,
                _registered_method=True)
        self.GetServerBalances = channel.unary_unary(
                '/project4Service/GetServerBalances',
                request_serializer=project4__pb2.BalancesRequest.SerializeToString,
                response_deserializer=project4__pb2.BalancesResponse.FromString,
                _registered_method=True)
        self.ViewChange = channel.unary_unary(
                '/project4Service/ViewChange',
                request_serializer=project4__pb2.ViewChangeRequest.SerializeToString,
                response_deserializer=project4__pb2.ViewChangeResponse.FromString,
                _registered_method=True)
        self.NewView = channel.unary_unary(
                '/project4Service/NewView',
                request_serializer=project4__pb2.NewViewRequest.SerializeToString,
                response_deserializer=project4__pb2.NewViewResponse.FromString,
                _registered_method=True)
        self.PrintLog = channel.unary_unary(
                '/project4Service/PrintLog',
                request_serializer=project4__pb2.PrintLogRequest.SerializeToString,
                response_deserializer=project4__pb2.PrintLogResponse.FromString,
                _registered_method=True)
        self.PrintStatus = channel.unary_unary(
                '/project4Service/PrintStatus',
                request_serializer=project4__pb2.PrintStatusRequest.SerializeToString,
                response_deserializer=project4__pb2.PrintStatusResponse.FromString,
                _registered_method=True)
        self.PrintView = channel.unary_unary(
                '/project4Service/PrintView',
                request_serializer=project4__pb2.PrintViewRequest.SerializeToString,
                response_deserializer=project4__pb2.PrintViewResponse.FromString,
                _registered_method=True)
        self.ChangeServerTimeout = channel.unary_unary(
                '/project4Service/ChangeServerTimeout',
                request_serializer=project4__pb2.ChangeServerTimeoutRequest.SerializeToString,
                response_deserializer=project4__pb2.ChangeServerTimeoutResponse.FromString,
                _registered_method=True)
        self.Transact = channel.unary_unary(
                '/project4Service/Transact',
                request_serializer=project4__pb2.TransactionRequest.SerializeToString,
                response_deserializer=project4__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.Promise = channel.unary_unary(
                '/project4Service/Promise',
                request_serializer=project4__pb2.PromiseRequest.SerializeToString,
                response_deserializer=project4__pb2.PromiseResponse.FromString,
                _registered_method=True)
        self.Acknowledge = channel.unary_unary(
                '/project4Service/Acknowledge',
                request_serializer=project4__pb2.AcknowledgeRequest.SerializeToString,
                response_deserializer=project4__pb2.AcknowledgeResponse.FromString,
                _registered_method=True)
        self.Accept = channel.unary_unary(
                '/project4Service/Accept',
                request_serializer=project4__pb2.AcceptRequest.SerializeToString,
                response_deserializer=project4__pb2.AcceptResponse.FromString,
                _registered_method=True)
        self.Accepted = channel.unary_unary(
                '/project4Service/Accepted',
                request_serializer=project4__pb2.AcceptedRequest.SerializeToString,
                response_deserializer=project4__pb2.AcceptedResponse.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/project4Service/GetBalance',
                request_serializer=project4__pb2.GetBalanceRequest.SerializeToString,
                response_deserializer=project4__pb2.GetBalanceResponse.FromString,
                _registered_method=True)
        self.GetLogs = channel.unary_unary(
                '/project4Service/GetLogs',
                request_serializer=project4__pb2.GetLogRequest.SerializeToString,
                response_deserializer=project4__pb2.GetLogResponse.FromString,
                _registered_method=True)
        self.GetDB = channel.unary_unary(
                '/project4Service/GetDB',
                request_serializer=project4__pb2.GetDBRequest.SerializeToString,
                response_deserializer=project4__pb2.GetDBResponse.FromString,
                _registered_method=True)
        self.UpdateDB = channel.unary_unary(
                '/project4Service/UpdateDB',
                request_serializer=project4__pb2.UpdateDBRequest.SerializeToString,
                response_deserializer=project4__pb2.UpdateDBResponse.FromString,
                _registered_method=True)
        self.GetPendingTransactions = channel.unary_unary(
                '/project4Service/GetPendingTransactions',
                request_serializer=project4__pb2.GetPendingTransactionsRequest.SerializeToString,
                response_deserializer=project4__pb2.GetPendingTransactionsResponse.FromString,
                _registered_method=True)
        self.SetPendingTransactions = channel.unary_unary(
                '/project4Service/SetPendingTransactions',
                request_serializer=project4__pb2.SetPendingTransactionsRequest.SerializeToString,
                response_deserializer=project4__pb2.SetPendingTransactionsResponse.FromString,
                _registered_method=True)
        self.SendDataStore = channel.unary_unary(
                '/project4Service/SendDataStore',
                request_serializer=project4__pb2.SendDataStoreRequest.SerializeToString,
                response_deserializer=project4__pb2.SendDataStoreResponse.FromString,
                _registered_method=True)
        self.ModifyDataStore = channel.unary_unary(
                '/project4Service/ModifyDataStore',
                request_serializer=project4__pb2.ModifyDataStoreRequest.SerializeToString,
                response_deserializer=project4__pb2.ModifyDataStoreResponse.FromString,
                _registered_method=True)
        self.Catchup = channel.unary_unary(
                '/project4Service/Catchup',
                request_serializer=project4__pb2.CatchupRequest.SerializeToString,
                response_deserializer=project4__pb2.CatchupResponse.FromString,
                _registered_method=True)
        self.ClientTransactionCrossShard = channel.unary_unary(
                '/project4Service/ClientTransactionCrossShard',
                request_serializer=project4__pb2.ClientTransactionCrossShardRequest.SerializeToString,
                response_deserializer=project4__pb2.ClientTransactionCrossShardResponse.FromString,
                _registered_method=True)
        self.GetDataStore = channel.unary_unary(
                '/project4Service/GetDataStore',
                request_serializer=project4__pb2.GetDataStoreRequest.SerializeToString,
                response_deserializer=project4__pb2.GetDataStoreResponse.FromString,
                _registered_method=True)
        self.sendDataStore = channel.unary_unary(
                '/project4Service/sendDataStore',
                request_serializer=project4__pb2.sendDataStoreRequest.SerializeToString,
                response_deserializer=project4__pb2.sendDataStoreResponse.FromString,
                _registered_method=True)
        self.BroadcastDataStoreCommit = channel.unary_unary(
                '/project4Service/BroadcastDataStoreCommit',
                request_serializer=project4__pb2.BroadcastDataStoreCommitRequest.SerializeToString,
                response_deserializer=project4__pb2.BroadcastDataStoreCommitResponse.FromString,
                _registered_method=True)
        self.sendData = channel.unary_unary(
                '/project4Service/sendData',
                request_serializer=project4__pb2.sendDataRequest.SerializeToString,
                response_deserializer=project4__pb2.sendDataResponse.FromString,
                _registered_method=True)
        self.send2PCommit = channel.unary_unary(
                '/project4Service/send2PCommit',
                request_serializer=project4__pb2.send2PCommitRequest.SerializeToString,
                response_deserializer=project4__pb2.send2PCommitResponse.FromString,
                _registered_method=True)
        self.send2PAck = channel.unary_unary(
                '/project4Service/send2PAck',
                request_serializer=project4__pb2.send2PAckRequest.SerializeToString,
                response_deserializer=project4__pb2.send2PAckResponse.FromString,
                _registered_method=True)
        self.ClientTransactionTripleCrossShard = channel.unary_unary(
                '/project4Service/ClientTransactionTripleCrossShard',
                request_serializer=project4__pb2.ClientTransactionTripleCrossShardRequest.SerializeToString,
                response_deserializer=project4__pb2.ClientTransactionTripleCrossShardResponse.FromString,
                _registered_method=True)


class project4ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClientTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicaPrePrepare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prepare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareBroadcast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitBroadcast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetServerState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerBalances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrintLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrintStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrintView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeServerTimeout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Promise(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Acknowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Accept(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Accepted(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """rpc Commit(CommitRequest) returns (CommitResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDB(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDB(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingTransactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPendingTransactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendDataStore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyDataStore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Catchup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientTransactionCrossShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDataStore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendDataStore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BroadcastDataStoreCommit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def send2PCommit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def send2PAck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientTransactionTripleCrossShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_project4ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClientTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientTransaction,
                    request_deserializer=project4__pb2.ClientTransactionRequest.FromString,
                    response_serializer=project4__pb2.ClientTransactionResponse.SerializeToString,
            ),
            'ReplicaPrePrepare': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicaPrePrepare,
                    request_deserializer=project4__pb2.PrePrepareRequest.FromString,
                    response_serializer=project4__pb2.PrePrepareResponse.SerializeToString,
            ),
            'Prepare': grpc.unary_unary_rpc_method_handler(
                    servicer.Prepare,
                    request_deserializer=project4__pb2.PrepareRequest.FromString,
                    response_serializer=project4__pb2.PrepareResponse.SerializeToString,
            ),
            'PrepareBroadcast': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareBroadcast,
                    request_deserializer=project4__pb2.PrepareBroadcastRequest.FromString,
                    response_serializer=project4__pb2.PrepareBroadcastResponse.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=project4__pb2.CommitRequest.FromString,
                    response_serializer=project4__pb2.CommitResponse.SerializeToString,
            ),
            'CommitBroadcast': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitBroadcast,
                    request_deserializer=project4__pb2.CommitBroadcastRequest.FromString,
                    response_serializer=project4__pb2.CommitBroadcastResponse.SerializeToString,
            ),
            'ResetServerState': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetServerState,
                    request_deserializer=project4__pb2.ResetServerStateRequest.FromString,
                    response_serializer=project4__pb2.ResetServerStateResponse.SerializeToString,
            ),
            'GetServerBalances': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerBalances,
                    request_deserializer=project4__pb2.BalancesRequest.FromString,
                    response_serializer=project4__pb2.BalancesResponse.SerializeToString,
            ),
            'ViewChange': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewChange,
                    request_deserializer=project4__pb2.ViewChangeRequest.FromString,
                    response_serializer=project4__pb2.ViewChangeResponse.SerializeToString,
            ),
            'NewView': grpc.unary_unary_rpc_method_handler(
                    servicer.NewView,
                    request_deserializer=project4__pb2.NewViewRequest.FromString,
                    response_serializer=project4__pb2.NewViewResponse.SerializeToString,
            ),
            'PrintLog': grpc.unary_unary_rpc_method_handler(
                    servicer.PrintLog,
                    request_deserializer=project4__pb2.PrintLogRequest.FromString,
                    response_serializer=project4__pb2.PrintLogResponse.SerializeToString,
            ),
            'PrintStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.PrintStatus,
                    request_deserializer=project4__pb2.PrintStatusRequest.FromString,
                    response_serializer=project4__pb2.PrintStatusResponse.SerializeToString,
            ),
            'PrintView': grpc.unary_unary_rpc_method_handler(
                    servicer.PrintView,
                    request_deserializer=project4__pb2.PrintViewRequest.FromString,
                    response_serializer=project4__pb2.PrintViewResponse.SerializeToString,
            ),
            'ChangeServerTimeout': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeServerTimeout,
                    request_deserializer=project4__pb2.ChangeServerTimeoutRequest.FromString,
                    response_serializer=project4__pb2.ChangeServerTimeoutResponse.SerializeToString,
            ),
            'Transact': grpc.unary_unary_rpc_method_handler(
                    servicer.Transact,
                    request_deserializer=project4__pb2.TransactionRequest.FromString,
                    response_serializer=project4__pb2.TransactionResponse.SerializeToString,
            ),
            'Promise': grpc.unary_unary_rpc_method_handler(
                    servicer.Promise,
                    request_deserializer=project4__pb2.PromiseRequest.FromString,
                    response_serializer=project4__pb2.PromiseResponse.SerializeToString,
            ),
            'Acknowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.Acknowledge,
                    request_deserializer=project4__pb2.AcknowledgeRequest.FromString,
                    response_serializer=project4__pb2.AcknowledgeResponse.SerializeToString,
            ),
            'Accept': grpc.unary_unary_rpc_method_handler(
                    servicer.Accept,
                    request_deserializer=project4__pb2.AcceptRequest.FromString,
                    response_serializer=project4__pb2.AcceptResponse.SerializeToString,
            ),
            'Accepted': grpc.unary_unary_rpc_method_handler(
                    servicer.Accepted,
                    request_deserializer=project4__pb2.AcceptedRequest.FromString,
                    response_serializer=project4__pb2.AcceptedResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=project4__pb2.GetBalanceRequest.FromString,
                    response_serializer=project4__pb2.GetBalanceResponse.SerializeToString,
            ),
            'GetLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogs,
                    request_deserializer=project4__pb2.GetLogRequest.FromString,
                    response_serializer=project4__pb2.GetLogResponse.SerializeToString,
            ),
            'GetDB': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDB,
                    request_deserializer=project4__pb2.GetDBRequest.FromString,
                    response_serializer=project4__pb2.GetDBResponse.SerializeToString,
            ),
            'UpdateDB': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDB,
                    request_deserializer=project4__pb2.UpdateDBRequest.FromString,
                    response_serializer=project4__pb2.UpdateDBResponse.SerializeToString,
            ),
            'GetPendingTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingTransactions,
                    request_deserializer=project4__pb2.GetPendingTransactionsRequest.FromString,
                    response_serializer=project4__pb2.GetPendingTransactionsResponse.SerializeToString,
            ),
            'SetPendingTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPendingTransactions,
                    request_deserializer=project4__pb2.SetPendingTransactionsRequest.FromString,
                    response_serializer=project4__pb2.SetPendingTransactionsResponse.SerializeToString,
            ),
            'SendDataStore': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDataStore,
                    request_deserializer=project4__pb2.SendDataStoreRequest.FromString,
                    response_serializer=project4__pb2.SendDataStoreResponse.SerializeToString,
            ),
            'ModifyDataStore': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyDataStore,
                    request_deserializer=project4__pb2.ModifyDataStoreRequest.FromString,
                    response_serializer=project4__pb2.ModifyDataStoreResponse.SerializeToString,
            ),
            'Catchup': grpc.unary_unary_rpc_method_handler(
                    servicer.Catchup,
                    request_deserializer=project4__pb2.CatchupRequest.FromString,
                    response_serializer=project4__pb2.CatchupResponse.SerializeToString,
            ),
            'ClientTransactionCrossShard': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientTransactionCrossShard,
                    request_deserializer=project4__pb2.ClientTransactionCrossShardRequest.FromString,
                    response_serializer=project4__pb2.ClientTransactionCrossShardResponse.SerializeToString,
            ),
            'GetDataStore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDataStore,
                    request_deserializer=project4__pb2.GetDataStoreRequest.FromString,
                    response_serializer=project4__pb2.GetDataStoreResponse.SerializeToString,
            ),
            'sendDataStore': grpc.unary_unary_rpc_method_handler(
                    servicer.sendDataStore,
                    request_deserializer=project4__pb2.sendDataStoreRequest.FromString,
                    response_serializer=project4__pb2.sendDataStoreResponse.SerializeToString,
            ),
            'BroadcastDataStoreCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastDataStoreCommit,
                    request_deserializer=project4__pb2.BroadcastDataStoreCommitRequest.FromString,
                    response_serializer=project4__pb2.BroadcastDataStoreCommitResponse.SerializeToString,
            ),
            'sendData': grpc.unary_unary_rpc_method_handler(
                    servicer.sendData,
                    request_deserializer=project4__pb2.sendDataRequest.FromString,
                    response_serializer=project4__pb2.sendDataResponse.SerializeToString,
            ),
            'send2PCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.send2PCommit,
                    request_deserializer=project4__pb2.send2PCommitRequest.FromString,
                    response_serializer=project4__pb2.send2PCommitResponse.SerializeToString,
            ),
            'send2PAck': grpc.unary_unary_rpc_method_handler(
                    servicer.send2PAck,
                    request_deserializer=project4__pb2.send2PAckRequest.FromString,
                    response_serializer=project4__pb2.send2PAckResponse.SerializeToString,
            ),
            'ClientTransactionTripleCrossShard': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientTransactionTripleCrossShard,
                    request_deserializer=project4__pb2.ClientTransactionTripleCrossShardRequest.FromString,
                    response_serializer=project4__pb2.ClientTransactionTripleCrossShardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'project4Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('project4Service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class project4Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClientTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/ClientTransaction',
            project4__pb2.ClientTransactionRequest.SerializeToString,
            project4__pb2.ClientTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicaPrePrepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/ReplicaPrePrepare',
            project4__pb2.PrePrepareRequest.SerializeToString,
            project4__pb2.PrePrepareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Prepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/Prepare',
            project4__pb2.PrepareRequest.SerializeToString,
            project4__pb2.PrepareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareBroadcast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/PrepareBroadcast',
            project4__pb2.PrepareBroadcastRequest.SerializeToString,
            project4__pb2.PrepareBroadcastResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/Commit',
            project4__pb2.CommitRequest.SerializeToString,
            project4__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitBroadcast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/CommitBroadcast',
            project4__pb2.CommitBroadcastRequest.SerializeToString,
            project4__pb2.CommitBroadcastResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetServerState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/ResetServerState',
            project4__pb2.ResetServerStateRequest.SerializeToString,
            project4__pb2.ResetServerStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerBalances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/GetServerBalances',
            project4__pb2.BalancesRequest.SerializeToString,
            project4__pb2.BalancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/ViewChange',
            project4__pb2.ViewChangeRequest.SerializeToString,
            project4__pb2.ViewChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NewView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/NewView',
            project4__pb2.NewViewRequest.SerializeToString,
            project4__pb2.NewViewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrintLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/PrintLog',
            project4__pb2.PrintLogRequest.SerializeToString,
            project4__pb2.PrintLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrintStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/PrintStatus',
            project4__pb2.PrintStatusRequest.SerializeToString,
            project4__pb2.PrintStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrintView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/PrintView',
            project4__pb2.PrintViewRequest.SerializeToString,
            project4__pb2.PrintViewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeServerTimeout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/ChangeServerTimeout',
            project4__pb2.ChangeServerTimeoutRequest.SerializeToString,
            project4__pb2.ChangeServerTimeoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/Transact',
            project4__pb2.TransactionRequest.SerializeToString,
            project4__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Promise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/Promise',
            project4__pb2.PromiseRequest.SerializeToString,
            project4__pb2.PromiseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Acknowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/Acknowledge',
            project4__pb2.AcknowledgeRequest.SerializeToString,
            project4__pb2.AcknowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Accept(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/Accept',
            project4__pb2.AcceptRequest.SerializeToString,
            project4__pb2.AcceptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Accepted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/Accepted',
            project4__pb2.AcceptedRequest.SerializeToString,
            project4__pb2.AcceptedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/GetBalance',
            project4__pb2.GetBalanceRequest.SerializeToString,
            project4__pb2.GetBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/GetLogs',
            project4__pb2.GetLogRequest.SerializeToString,
            project4__pb2.GetLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/GetDB',
            project4__pb2.GetDBRequest.SerializeToString,
            project4__pb2.GetDBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/UpdateDB',
            project4__pb2.UpdateDBRequest.SerializeToString,
            project4__pb2.UpdateDBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/GetPendingTransactions',
            project4__pb2.GetPendingTransactionsRequest.SerializeToString,
            project4__pb2.GetPendingTransactionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPendingTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/SetPendingTransactions',
            project4__pb2.SetPendingTransactionsRequest.SerializeToString,
            project4__pb2.SetPendingTransactionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendDataStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/SendDataStore',
            project4__pb2.SendDataStoreRequest.SerializeToString,
            project4__pb2.SendDataStoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModifyDataStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/ModifyDataStore',
            project4__pb2.ModifyDataStoreRequest.SerializeToString,
            project4__pb2.ModifyDataStoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Catchup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/Catchup',
            project4__pb2.CatchupRequest.SerializeToString,
            project4__pb2.CatchupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClientTransactionCrossShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/ClientTransactionCrossShard',
            project4__pb2.ClientTransactionCrossShardRequest.SerializeToString,
            project4__pb2.ClientTransactionCrossShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDataStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/GetDataStore',
            project4__pb2.GetDataStoreRequest.SerializeToString,
            project4__pb2.GetDataStoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def sendDataStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/sendDataStore',
            project4__pb2.sendDataStoreRequest.SerializeToString,
            project4__pb2.sendDataStoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BroadcastDataStoreCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/BroadcastDataStoreCommit',
            project4__pb2.BroadcastDataStoreCommitRequest.SerializeToString,
            project4__pb2.BroadcastDataStoreCommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def sendData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/sendData',
            project4__pb2.sendDataRequest.SerializeToString,
            project4__pb2.sendDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def send2PCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/send2PCommit',
            project4__pb2.send2PCommitRequest.SerializeToString,
            project4__pb2.send2PCommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def send2PAck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/send2PAck',
            project4__pb2.send2PAckRequest.SerializeToString,
            project4__pb2.send2PAckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClientTransactionTripleCrossShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project4Service/ClientTransactionTripleCrossShard',
            project4__pb2.ClientTransactionTripleCrossShardRequest.SerializeToString,
            project4__pb2.ClientTransactionTripleCrossShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
