// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: api/replica.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReplicaTransport_Send_FullMethodName = "/replica.ReplicaTransport/Send"
)

// ReplicaTransportClient is the client API for ReplicaTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ReplicaTransport carries signed replica-to-replica messages.
type ReplicaTransportClient interface {
	Send(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*SendAck, error)
}

type replicaTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicaTransportClient(cc grpc.ClientConnInterface) ReplicaTransportClient {
	return &replicaTransportClient{cc}
}

func (c *replicaTransportClient) Send(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*SendAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendAck)
	err := c.cc.Invoke(ctx, ReplicaTransport_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicaTransportServer is the server API for ReplicaTransport service.
// All implementations must embed UnimplementedReplicaTransportServer
// for forward compatibility.
//
// ReplicaTransport carries signed replica-to-replica messages.
type ReplicaTransportServer interface {
	Send(context.Context, *Envelope) (*SendAck, error)
	mustEmbedUnimplementedReplicaTransportServer()
}

// UnimplementedReplicaTransportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplicaTransportServer struct{}

func (UnimplementedReplicaTransportServer) Send(context.Context, *Envelope) (*SendAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedReplicaTransportServer) mustEmbedUnimplementedReplicaTransportServer() {}
func (UnimplementedReplicaTransportServer) testEmbeddedByValue()                          {}

// UnsafeReplicaTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicaTransportServer will
// result in compilation errors.
type UnsafeReplicaTransportServer interface {
	mustEmbedUnimplementedReplicaTransportServer()
}

func RegisterReplicaTransportServer(s grpc.ServiceRegistrar, srv ReplicaTransportServer) {
	// If the following call panics, it indicates UnimplementedReplicaTransportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReplicaTransport_ServiceDesc, srv)
}

func _ReplicaTransport_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Envelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaTransportServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicaTransport_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaTransportServer).Send(ctx, req.(*Envelope))
	}
	return interceptor(ctx, in, info, handler)
}

// ReplicaTransport_ServiceDesc is the grpc.ServiceDesc for ReplicaTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReplicaTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "replica.ReplicaTransport",
	HandlerType: (*ReplicaTransportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _ReplicaTransport_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/replica.proto",
}
