// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: api/replica.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope is the signed wire message exchanged between replicas.
// The signature covers sender_id, type, and payload (not the signature field).
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int32                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_api_replica_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_replica_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_api_replica_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Envelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type SendAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAck) Reset() {
	*x = SendAck{}
	mi := &file_api_replica_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAck) ProtoMessage() {}

func (x *SendAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_replica_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAck.ProtoReflect.Descriptor instead.
func (*SendAck) Descriptor() ([]byte, []int) {
	return file_api_replica_proto_rawDescGZIP(), []int{1}
}

func (x *SendAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SendAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_replica_proto protoreflect.FileDescriptor

const file_api_replica_proto_rawDesc = "" +
	"\n" +
	"\x11api/replica.proto\x12\areplica\"s\n" +
	"\bEnvelope\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x05R\bsenderId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"/\n" +
	"\aSendAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2?\n" +
	"\x10ReplicaTransport\x12+\n" +
	"\x04Send\x12\x11.replica.Envelope\x1a\x10.replica.SendAckB7Z5github.com/KashMaj1708/2pcbyz-kashmaj1708/internal/pbb\x06proto3"

var (
	file_api_replica_proto_rawDescOnce sync.Once
	file_api_replica_proto_rawDescData []byte
)

func file_api_replica_proto_rawDescGZIP() []byte {
	file_api_replica_proto_rawDescOnce.Do(func() {
		file_api_replica_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_replica_proto_rawDesc), len(file_api_replica_proto_rawDesc)))
	})
	return file_api_replica_proto_rawDescData
}

var file_api_replica_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_replica_proto_goTypes = []any{
	(*Envelope)(nil), // 0: replica.Envelope
	(*SendAck)(nil),  // 1: replica.SendAck
}
var file_api_replica_proto_depIdxs = []int32{
	0, // 0: replica.ReplicaTransport.Send:input_type -> replica.Envelope
	1, // 1: replica.ReplicaTransport.Send:output_type -> replica.SendAck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_replica_proto_init() }
func file_api_replica_proto_init() {
	if File_api_replica_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_replica_proto_rawDesc), len(file_api_replica_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_replica_proto_goTypes,
		DependencyIndexes: file_api_replica_proto_depIdxs,
		MessageInfos:      file_api_replica_proto_msgTypes,
	}.Build()
	File_api_replica_proto = out.File
	file_api_replica_proto_goTypes = nil
	file_api_replica_proto_depIdxs = nil
}
